[package]
name = "remotefs-gcs"
version = "0.1.0"
authors = ["Christian Visintin <christian.visintin@veeso.dev>"]
categories = ["filesystem", "network-programming"]
edition = "2024"
homepage = "https://github.com/remotefs-rs/remotefs-rs-gcs"
include = [
  "/CHANGELOG.md",
  "/Cargo.lock",
  "/Cargo.toml",
  "/LICENSE",
  "/README.md",
  "/src/**",
]
keywords = [
  "gcs",
  "google-cloud",
  "google-cloud-storage",
  "remotefs",
  "storage",
]
license = "MIT"
readme = "README.md"
repository = "https://github.com/remotefs-rs/remotefs-rs-gcs"
rust-version = "1.98.0"
description = "Google Cloud Storage client for remotefs-rs."

[features]
default = ["find"]
find = ["remotefs/find"]
no-log = ["log/max_level_off"]
with-containers = []
with-gcs-ci = []

[dependencies]
bytes = "1"
google-cloud-auth = "1"
google-cloud-gax = "1"
google-cloud-storage = "1"
log = "0.4"
remotefs = "0.3"
tokio = { version = "1", features = ["rt", "rt-multi-thread"] }

[dev-dependencies]
env_logger = "0.11"
pretty_assertions = "1"
rand = "0.10"
tempfile = "3"
testcontainers = { version = "0.28", features = ["blocking", "http_wait"] }

[lib]
name = "remotefs_gcs"
path = "src/lib.rs"

[target."cfg(target_os = \"windows\")"]
[target."cfg(target_os = \"windows\")".dependencies]
path-slash = "^0.2"

[lints.rust]
ambiguous_negative_literals = "warn"
missing_debug_implementations = "warn"
redundant_imports = "warn"
redundant_lifetimes = "warn"
trivial_numeric_casts = "warn"
unsafe_op_in_unsafe_fn = "warn"
unused_lifetimes = "warn"

[lints.clippy]
cargo = { level = "warn", priority = -1 }
complexity = { level = "warn", priority = -1 }
correctness = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
perf = { level = "warn", priority = -1 }
style = { level = "warn", priority = -1 }
suspicious = { level = "warn", priority = -1 }
allow_attributes_without_reason = "warn"
as_pointer_underscore = "warn"
assertions_on_result_states = "warn"
clone_on_ref_ptr = "warn"
deref_by_slicing = "warn"
disallowed_script_idents = "warn"
empty_drop = "warn"
empty_enum_variants_with_brackets = "warn"
empty_structs_with_brackets = "warn"
fn_to_numeric_cast_any = "warn"
if_then_some_else_none = "warn"
literal_string_with_formatting_args = "allow"
map_err_ignore = "warn"
multiple_crate_versions = "allow"
negative_feature_names = "allow"
redundant_feature_names = "allow"
redundant_type_annotations = "warn"
renamed_function_params = "warn"
semicolon_outside_block = "warn"
undocumented_unsafe_blocks = "warn"
unnecessary_safety_comment = "warn"
unnecessary_safety_doc = "warn"
unneeded_field_pattern = "warn"
unused_result_ok = "warn"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
